# Generated by Django 4.0.6 on 2023-10-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='custom_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
