# Generated by Django 4.0.6 on 2023-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreports', '0003_alter_patient_sex_alter_serology_aso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverfunctiontest',
            name='indirect',
            field=models.FloatField(blank=True, help_text='Up to 0.4 mg/dl', null=True),
        ),
    ]
