# Generated by Django 4.0.6 on 2023-10-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labreports', '0004_liverfunctiontest_indirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='bt',
            field=models.FloatField(blank=True, help_text='(2-7)Min)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='ct',
            field=models.FloatField(blank=True, help_text='(5-11)Min', max_length=10, null=True),
        ),
    ]
